Add a dynamic custom type collection
bestit/commercetools-custom-types-bundle pull request #1
Opened 2017-03-14 13:50 UTC by migo315

Im Projekt werden zum Teil die definierten Keys benötigt. Damit ich diese in der config.yml nicht zusätzlich und somit doppelt definieren muss, habe ich diese entsprechenden Erweiterungen hinzugefügt.

Die Collection sammelt alle definierten custom types keys und speichert diese ab - so dass ich später in den Servcies mit der Resource (zb. "order") den Key Namen erhalte. Die Ressourcen sind von CT fest definiert, daher eignen diese sich zum suchen.
Alle derzeit verfügbaren Resourcen (laut Doku) sind auch in der ResourceType Enum zur Verfügung gestellt worden.

2017-03-14 14:55 UTC, b3nl commented
@migo315 http://www.php-fig.org/psr/psr-2/#files the blank line at the end is missing.

2017-03-14 14:58 UTC, b3nl requested changes
Please check!

2017-03-14 14:58 UTC, b3nl commented on src/Collection/CustomTypeCollection.php
> +class CustomTypeCollection
I would have implemented something like an arrayaccess interface ´.... but ok.

2017-03-14 14:58 UTC, b3nl commented on src/Collection/CustomTypeCollection.php
> +    private $collection;
You start with void and not array. it still could be void, even on the first get or has call.

2017-03-14 16:02 UTC, migo315 reviewed
PR updated

2017-03-14 16:02 UTC, migo315 commented on src/Collection/CustomTypeCollection.php
> +class CustomTypeCollection
ArrayAccess is implemented now

2017-03-14 16:02 UTC, migo315 commented on src/Collection/CustomTypeCollection.php
> +    private $collection;
One mistake - the property should never be null ... and "void" least at all ;-)

2017-03-16 07:50 UTC, b3nl approved these changes
I don't understand yet why you implemented extra complexity but will merge it anyway,

2017-03-16 07:53 UTC, merged

2017-03-16 09:45 UTC, migo315 commented
Which extra complexity? the second model? Maybe we want to extend the functionality. So i decide to use an object immediately instead of use an array which maybe change to object in future (which would not be backwards compatible.)

By the way: My tag (0.5.1) is missing. Can you tag it?